# Generated by Django 4.1.7 on 2023-03-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='completed_payments',
            new_name='completed_payment',
        ),
        migrations.RenameModel(
            old_name='ongoing_payments',
            new_name='ongoing_payment',
        ),
    ]
