# Generated by Django 4.1.7 on 2023-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0002_rename_completed_payments_completed_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoing_payment',
            name='order_id',
            field=models.CharField(default='2S188728RX530104L', max_length=256),
        ),
    ]
