# Generated by Django 4.1.7 on 2023-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0003_ongoing_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoing_payment',
            name='order_id',
            field=models.CharField(max_length=256),
        ),
    ]
