# Generated by Django 4.1.7 on 2023-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0004_alter_ongoing_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_payment',
            name='created_at',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='completed_payment',
            name='updated_at',
            field=models.CharField(max_length=256),
        ),
    ]
