# Generated by Django 4.1.7 on 2023-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0008_auto_20230308_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=256)),
                ('pp_id', models.CharField(max_length=36)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='completed_payment',
        ),
        migrations.DeleteModel(
            name='ongoing_payment',
        ),
    ]
