# Generated by Django 4.1.7 on 2023-03-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0009_payments_delete_completed_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='amount',
        ),
    ]
