# Generated by Django 4.1.7 on 2023-04-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('origin', models.TextField()),
                ('destination', models.TextField()),
                ('info', models.JSONField(blank=True, null=True)),
                ('available_sits', models.IntegerField()),
                ('starting_date', models.DateTimeField()),
                ('owner_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('pickup_location', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directions.trip')),
            ],
        ),
    ]
